<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ./Mecha.glb --shadows
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations, Edges } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/Mecha.glb')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)
  $: $actions['Idle_Base']?.play()

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="model" rotation={[-Math.PI, 0, 0]} scale={-0.025} >
        <T is={gltf.nodes.Root} />
        <T is={gltf.nodes.C_Buffbone_Glb_Layout_Loc} />
        <T is={gltf.nodes.C_Buffbone_Glb_Center_Loc} />
        <T is={gltf.nodes.Buffbone_Glb_Ground_Loc} />
        <T is={gltf.nodes.C_Buffbone_Glb_Overhead_Loc} />
        <T is={gltf.nodes.Buffbone_Glb_Channel_Loc} />
        <T is={gltf.nodes.Buffbone_Glb_Weapon_1} />
        <T is={gltf.nodes.Buffbone_Cstm_Healthbar} />
        <T is={gltf.nodes.Photo} />
        <T.Group name="Mesh_0">
          <T.SkinnedMesh
            name="Mesh_0_1"
            castShadow
            receiveShadow
            geometry={gltf.nodes.Mesh_0_1.geometry}
            material={gltf.materials.Sett_Skin01_MAT}
            skeleton={gltf.nodes.Mesh_0_1.skeleton}
          />
         <!--  <T.SkinnedMesh
            name="Mesh_0_2"
            castShadow
            receiveShadow
            geometry={gltf.nodes.Mesh_0_2.geometry}
            material={gltf.materials.Joke}
            skeleton={gltf.nodes.Mesh_0_2.skeleton}
          /> -->
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}
  <slot {ref} />
</T>
